# Quiz 4

<font size='4'>

BIOS-584<br>
Nov 21, 2025

* Write down your name in a Markdown section.

Paige Toth

In [3]:
import numpy as np
import pandas as pd
import os

## Preliminary

<font size='4'>
    
* There are six files stored under `Your own GitHub repository/data/Quiz4`.
* Import those six files using relevant functions in `Pandas`.

the current working directory is: C:\Users\paige\OneDrive\Documents\GitHub\BIOS-584\data\Quiz4

## Import Data

<font size='4'>

* Three lists named `study_id_ls`, `measure_date_ls`, and `duration_ls` have been initialized.
* Write a for loop to extract and append the values of `study_id`, `measure_date`, and `duration` to `study_id_ls`, `measure_date_ls`, and `duration_ls`, respectively.

<font size='4'>

* Create a new Pandas Dataframe combining three lists and name it `input_df`.

   study_id measure_date  duration
0         1   2025-01-01       100
1         1   2025-03-01       300
2         1   2025-02-01       200
3         1   2025-11-01        25
4         1   2025-11-01        20
5         1   2025-11-03        30

<font size='4'>

* Show or print `input_df`

   study_id measure_date  duration
0         1   2025-01-01       100
1         1   2025-03-01       300
2         1   2025-02-01       200
3         1   2025-11-01        25
4         1   2025-11-01        20
5         1   2025-11-03        30

## Data Manipulation

<font size='4'>

* Reorder the dataframe by `measure_date` (earliest to latest) and then by `duration` (shortest to longest).

   study_id measure_date  duration
4         1   2025-11-01        20
3         1   2025-11-01        25
5         1   2025-11-03        30
0         1   2025-01-01       100
2         1   2025-02-01       200
1         1   2025-03-01       300

<font size='4'>

* Create a new column called `relative_time` by calculating the time difference in days between each of the measure date and the earliest one.

<font size='4'>

* Reset the index column and remove the old index.

## Final Data Visualization
<font size='4'>
    
* Display the final `input_df`.

   study_id measure_date  duration  relative_time
0         1   2025-11-01        20            304
1         1   2025-11-01        25            304
2         1   2025-11-03        30            306
3         1   2025-01-01       100              0
4         1   2025-02-01       200             31
5         1   2025-03-01       300             59