# Quiz 4

<font size='4'>

BIOS-584<br>
Nov 21, 2025

* Write down your name in a Markdown section.

Paige Toth

In [15]:
import numpy as np
import pandas as pd
import os

## Preliminary

<font size='4'>
    
* There are six files stored under `Your own GitHub repository/data/Quiz4`.
* Import those six files using relevant functions in `Pandas`.

In [36]:
#finding current working directory
current_directory = os.getcwd()
print(f"The current working directory is: {current_directory}")

quiz4_files = r'C:\Users\paige\OneDrive\Documents\GitHub\BIOS-584\data\Quiz4'

#changing current working directory to the quiz 4 directory
os.chdir(quiz4_files)

#reading in the six files
df_list = []

for i in range (1,7):
    file = f"data_{i}.txt"
    df = pd.read_csv(file)
    df_list.append(df)
print(df_list) #checking work

#printing as table
df_list

The current working directory is: C:\Users\paige\OneDrive\Documents\GitHub\BIOS-584\data\Quiz4
[   study_id measure_date  duration
0         1   2025-01-01       100,    study_id measure_date  duration
0         1   2025-03-01       300,    study_id measure_date  duration
0         1   2025-02-01       200,    study_id measure_date  duration
0         1   2025-11-01        25,    study_id measure_date  duration
0         1   2025-11-01        20,    study_id measure_date  duration
0         1   2025-11-03        30]

[   study_id measure_date  duration
 0         1   2025-01-01       100,
    study_id measure_date  duration
 0         1   2025-03-01       300,
    study_id measure_date  duration
 0         1   2025-02-01       200,
    study_id measure_date  duration
 0         1   2025-11-01        25,
    study_id measure_date  duration
 0         1   2025-11-01        20,
    study_id measure_date  duration
 0         1   2025-11-03        30]

## Import Data

<font size='4'>

* Three lists named `study_id_ls`, `measure_date_ls`, and `duration_ls` have been initialized.
* Write a for loop to extract and append the values of `study_id`, `measure_date`, and `duration` to `study_id_ls`, `measure_date_ls`, and `duration_ls`, respectively.

In [37]:
#creating empty lists for the study, measure date, and duration lists
study_id_ls = []
measure_date_ls = []
duration_ls = []

#for-loop to append data to the empty lists
for df in df_list:
    study_id_ls.extend(df.study_id.tolist())
    measure_date_ls.extend(df.measure_date.tolist())
    duration_ls.extend(df.duration.tolist())

print(study_id_ls)
print(measure_date_ls)
print(duration_ls)

[1, 1, 1, 1, 1, 1]
['2025-01-01', '2025-03-01', '2025-02-01', '2025-11-01', '2025-11-01', '2025-11-03']
[100, 300, 200, 25, 20, 30]

<font size='4'>

* Create a new Pandas Dataframe combining three lists and name it `input_df`.

In [18]:
#creating new dataframe combining the lists
input_df = pd.DataFrame({"study_id": study_id_ls,
       "measure_date": measure_date_ls,
       "duration": duration_ls
      })

#checking work
print(input_df)

#printing in readable table
input_df

   study_id measure_date  duration
0         1   2025-01-01       100
1         1   2025-03-01       300
2         1   2025-02-01       200
3         1   2025-11-01        25
4         1   2025-11-01        20
5         1   2025-11-03        30

   study_id measure_date  duration
0         1   2025-01-01       100
1         1   2025-03-01       300
2         1   2025-02-01       200
3         1   2025-11-01        25
4         1   2025-11-01        20
5         1   2025-11-03        30

<font size='4'>

* Show or print `input_df`

In [19]:
#showing input_df as a table again
input_df

   study_id measure_date  duration
0         1   2025-01-01       100
1         1   2025-03-01       300
2         1   2025-02-01       200
3         1   2025-11-01        25
4         1   2025-11-01        20
5         1   2025-11-03        30

## Data Manipulation

<font size='4'>

* Reorder the dataframe by `measure_date` (earliest to latest) and then by `duration` (shortest to longest).

In [29]:
#sorting measure_date from earliest date to latest date (ascending)
input_df = input_df.sort_values(by="measure_date", ascending = True)

#showing as a table
input_df

#soritng duration from the shortest duration to the longest duration (ascending)
input_df = input_df.sort_values(by="duration", ascending = True)

#showing as a table
input_df

   study_id measure_date  duration
0         1   2025-11-01        20
1         1   2025-11-01        25
2         1   2025-11-03        30
3         1   2025-01-01       100
4         1   2025-02-01       200
5         1   2025-03-01       300

<font size='4'>

* Create a new column called `relative_time` by calculating the time difference in days between each of the measure date and the earliest one.

In [38]:
#creating relative_time column by calculating the difference in time for each date measure versus the earliest date

#importing datetime/date so that the dates will correctly substract and calculate
from datetime import date

input_df['measure_date'] = pd.to_datetime(input_df['measure_date'])

#pulling the earliest date recorded
earliest_date = input_df['measure_date'].min()
input_df['relative_time'] = (input_df['measure_date'] - earliest_date).dt.days

#checking work

input_df

   study_id measure_date  duration  relative_time
0         1   2025-11-01        20            304
1         1   2025-11-01        25            304
2         1   2025-11-03        30            306
3         1   2025-01-01       100              0
4         1   2025-02-01       200             31
5         1   2025-03-01       300             59

<font size='4'>

* Reset the index column and remove the old index.

In [39]:
input_df = input_df.reset_index(drop=True)

## Final Data Visualization
<font size='4'>
    
* Display the final `input_df`.

In [40]:
#displaying table of reset index
input_df

   study_id measure_date  duration  relative_time
0         1   2025-11-01        20            304
1         1   2025-11-01        25            304
2         1   2025-11-03        30            306
3         1   2025-01-01       100              0
4         1   2025-02-01       200             31
5         1   2025-03-01       300             59